Allow forcing creation of a swapfile on unencrypted systems, don't remove swapfile if unnecessary, wording adjustments

diff --git a/usr/share/swap-file-creator/swap-file-creator b/usr/share/swap-file-creator/swap-file-creator
--- a/usr/share/swap-file-creator/swap-file-creator
+++ b/usr/share/swap-file-creator/swap-file-creator
@@ -20,6 +20,9 @@ set -o nounset
 LC_ALL=C
 export LC_ALL
 
+do_luks_check='true'
+luks_check_passed='false'
+
 error_handler() {
    local exit_code="$?"
    trap "" ERR
@@ -98,54 +101,61 @@ set_defaults() {
   [[ -v "SWAP_FILE_SIZE_CUSTOM_MB" ]] || SWAP_FILE_SIZE_CUSTOM_MB=""
 }
 
-bail_if_swap_not_on_luks() {
+check_swap_on_luks() {
    local swap_mount_device swap_mount_real_device swap_mount_slave_dev \
       blkid_swap_mount_fs
+
+   if [ "$do_luks_check" = 'false' ] \
+      || [ "$luks_check_passed" = 'true' ]; then
+      return 0
+   fi
 
    swap_mount_device="$(findmnt -n --output=SOURCE --target "$(dirname "$SWAPFILE")")" || true
    if [ -z "$swap_mount_device" ]; then
       printf '%s\n' "ERROR: No mountpoint source device found for swapfile '$SWAPFILE'!" >&2
-      exit 1
+      return 2
    fi
    if ! [[ "$swap_mount_device" = '/dev/mapper/'* ]]; then
-      printf '%s\n' "INFO: Swapfile mountpoint source device '$swap_mount_device' is not a device-mapper device, exiting, ok."
-      exit 0
+      printf '%s\n' "INFO: Swapfile mountpoint source device '$swap_mount_device' is not a device-mapper device, ok."
+      return 1
    fi
 
    swap_mount_real_device="$(readlink -f "$swap_mount_device")" || true
    if [ -z "$swap_mount_real_device" ]; then
       printf '%s\n' "ERROR: Cannot find true source device for swapfile mountpoint device '$swap_mount_device'!" >&2
-      exit 1
+      return 2
    fi
    swap_mount_real_device="$(basename "$swap_mount_real_device")"
 
    if ! [[ "$swap_mount_real_device" = dm-* ]]; then
-      printf '%s\n' "ERROR: Swapfile mountpoint source device '/dev/$swap_mount_real_device' is not a device-mapper device, exiting, ok." >&2
-      exit 1
+      printf '%s\n' "ERROR: Swapfile mountpoint source device '/dev/$swap_mount_real_device' is not a device-mapper device!" >&2
+      return 2
    fi
 
    swap_mount_slave_dev="$(find "/sys/block/$swap_mount_real_device/slaves" -mindepth 1)"
    if [ "$(wc -l <<< "$swap_mount_slave_dev")" != '1' ]; then
-      printf '%s\n' "INFO: Swapfile mountpoint source device '$swap_mount_device' has an incorrect number of slave devices to be a LUKS device, exiting, ok."
+      printf '%s\n' "INFO: Swapfile mountpoint source device '$swap_mount_device' has an incorrect number of slave devices to be a LUKS device, ok."
       printf '%s\n' "Slave devices:"
       printf '%s\n' "$swap_mount_slave_dev"
-      exit 0
+      return 1
    fi
    swap_mount_slave_dev="$(basename "$swap_mount_slave_dev")"
    if ! [ -b "/dev/$swap_mount_slave_dev" ]; then
       printf '%s\n' "ERROR: Swapfile mountpoint underlying device '/dev/$swap_mount_slave_dev' does not exist!" >&2
-      exit 1
+      return 2
    fi
 
    blkid_swap_mount_fs="$(blkid -s TYPE -o value "/dev/$swap_mount_slave_dev")"
    if [ -z "$blkid_swap_mount_fs" ]; then
-      printf '%s\n' "INFO: 'blkid' did not return the filesystem on swapfile mountpoint underlying device '/dev/$swap_mount_slave_dev', exiting, ok."
-      exit 0
+      printf '%s\n' "INFO: 'blkid' did not return the filesystem on swapfile mountpoint underlying device '/dev/$swap_mount_slave_dev', ok."
+      return 1
    fi
    if [ "$blkid_swap_mount_fs" != 'crypto_LUKS' ]; then
-      printf '%s\n' "INFO: Swapfile mountpoint underlying device '/dev/$swap_mount_slave_dev' is not a LUKS device, exiting, ok."
-      exit 0
+      printf '%s\n' "INFO: Swapfile mountpoint underlying device '/dev/$swap_mount_slave_dev' is not a LUKS device, ok."
+      return 1
    fi
+
+   luks_check_passed='true'
 }
 
 do_stop() {
@@ -172,7 +182,7 @@ do_stop() {
          fi
       fi
 
-      if [ -f "$SWAPFILE" ]; then
+      if [ -f "$SWAPFILE" ] && ! check_swap_on_luks; then
          printf '%s\n' "INFO: Removing '$SWAPFILE'..."
          safe-rm --force -- "$SWAPFILE"
          printf '%s\n' "INFO: Done removing '$SWAPFILE'."
@@ -198,7 +208,19 @@ do_start() {
       fi
    fi
 
-   bail_if_swap_not_on_luks
+   luks_check_returncode='0'
+   check_swap_on_luks || luks_check_returncode="$?"
+   case "$luks_check_returncode" in
+      2)
+         exit 1
+         ;;
+      1)
+         exit 0
+         ;;
+      *)
+         true
+         ;;
+   esac
 
    if [ "$systemd_detect_virt_output" = "xen" ]; then
       printf '%s\n' "INFO: xen detected. Could be a Qubes HVM. Skipping swap-file-creator. Doing nothing, ok."
@@ -364,8 +386,28 @@ set_defaults
 
 if [ $# -eq 0 ]; then
     printf '%s\n' "ERROR: No arguments provided." >&2
-    printf '%s\n' "Usage: $0 [start|stop]" >&2
+    printf '%s\n' "Usage: $0 [--force] (start|stop)" >&2
     exit 1
+fi
+
+while [ -n "${1:-}" ]; do
+   case "$1" in
+      --force)
+         do_luks_check='false'
+         shift
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         break
+         ;;
+   esac
+done
+
+if [ -z "${1:-}" ]; then
+   printf '%s\n' "ERROR: No mode provided." >&2
 fi
 
 case "$1" in
@@ -377,7 +419,7 @@ case "$1" in
         ;;
     *)
         printf '%s\n' "ERROR: Invalid argument: $1" >&2
-        printf '%s\n' "Usage: $0 [start|stop]" >&2
+        printf '%s\n' "Usage: $0 [--force] (start|stop)" >&2
         exit 1
         ;;
 esac
