output

diff --git a/usr/share/swap-file-creator/swap-file-creator b/usr/share/swap-file-creator/swap-file-creator
--- a/usr/share/swap-file-creator/swap-file-creator
+++ b/usr/share/swap-file-creator/swap-file-creator
@@ -41,6 +41,7 @@ error_handler() {
 ## Clean the output and submit to developers.
 ##
 ## See also:
+## This does not indicate a system compromise. The system can run without a swap file.
 ## https://www.kicksecure.com/wiki/swap-file-creator
 ###############################################################################\
 " >&2
@@ -145,9 +146,9 @@ do_stop() {
    fi
 
    if [ "$SHRED_ON_STOP" = "yes" ]; then
-      printf '%s\n' "INFO: Shredding '$SWAPFILE'... This may take a while..."
+      printf '%s\n' "INFO: Shredding '$SWAPFILE' before removal... This may take a while..."
       shred $SHRED_OPTS "$SWAPFILE"
-      printf '%s\n' "INFO: Done shred '$SWAPFILE'."
+      printf '%s\n' "INFO: Done shredding '$SWAPFILE'."
    fi
 
    ## TODO: Why is this needed?
@@ -170,7 +171,7 @@ do_start() {
    printf '%s\n' "INFO: swap-file-creator..."
 
    if ! [[ "$SWAPFILE" = /* ]]; then
-      printf '%s\n' "ERROR: 'SWAPFILE' value '$SWAPFILE' is not an absolute path!" >&2
+      printf '%s\n' "ERROR: 'SWAPFILE' value '$SWAPFILE' is not an absolute path. Swap file not enabled." >&2
       exit 1
    fi
 
@@ -193,12 +194,12 @@ do_start() {
 
    if [ "$DO_PRE_CHECK" = 'yes' ]; then
       if [ "$systemd_detect_virt_output" = "xen" ]; then
-         printf '%s\n' "INFO: Virtualizer 'xen' detected. Could be 'Qubes'. Skipping swap-file-creator. Doing nothing, ok."
+         printf '%s\n' "INFO: Virtualizer 'xen' detected. Could be 'Qubes'. Skipping swap-file-creator (no swap file will be created). Doing nothing, ok."
          exit 0
       fi
 
       if ! luks-path-check "$SWAPFILE" &>/dev/null ; then
-         printf '%s\n' "INFO: File '$SWAPFILE' on LUKS encrypted device: 'no'. - Doing nothing, ok. See also: https://www.kicksecure.com/wiki/swap"
+         printf '%s\n' "INFO: LUKS encrypted device for file '$SWAPFILE': no. Not creating a swap file (expected). Doing nothing, OK. See also: https://www.kicksecure.com/wiki/swap"
          exit 0
       else
          pre_check_done='true'
@@ -239,10 +240,10 @@ do_start() {
    swap_file_actual_size_in_mb="$(( swap_file_actual_size_in_mb + 2 ))"
 
    if [ "$total_ram_in_mb" -ge "$ENOUGH_RAM" ]; then
-      printf '%s\n' "INFO: Enough RAM available. More than $ENOUGH_RAM MB RAM. OK."
+      printf '%s\n' "INFO: Enough RAM available (>= $ENOUGH_RAM MB). OK."
    else
-      printf '%s\n' "INFO: Less than $ENOUGH_RAM MB RAM available."
-      printf '%s\n' "INFO: Ideally you should assign 2048 MB (2 GB) or more RAM to this machine."
+      printf '%s\n' "INFO: Low RAM detected (< $ENOUGH_RAM MB)."
+      printf '%s\n' "INFO: Consider assigning 2048 MB (2 GB) or more RAM to this machine."
       printf '%s\n' "INFO: See: https://www.kicksecure.com/wiki/swap-file-creator"
    fi
 
@@ -274,7 +275,7 @@ do_start() {
    free_disk_space_in_gb_plus=$(( free_disk_space_in_gb + 2 ))
 
    if [ "$swap_file_size_gb" -ge "$free_disk_space_in_gb_plus" ]; then
-      printf '%s\n' "ERROR: Only $free_disk_space_in_gb GB free disk space. Insufficient to create $swap_file_size_gb GB sized swap file." >&2
+      printf '%s\n' "ERROR: Only $free_disk_space_in_gb GB free disk space. Insufficient to create $swap_file_size_gb GB sized swap file. Swap file not enabled." >&2
       exit 1
    fi
 
@@ -347,11 +348,11 @@ do_start() {
       swap_file_kernel_reported_size_gb=$(bc <<< "scale=2; $swap_file_size_in_mb / 1024")
    else
       printf '%s\n' "\
-WARNING: Minor issue.
-Unit test if swap file with correct size has been created has been skipped.
+INFO: Minor note (not an error).
+Swap file has been enabled; the size self-check was skipped.
 Output of:
     swapon --noheadings --raw --show=NAME,SIZE
-showed unknown unit for file '$SWAPFILE', not M or G.
+reported an unexpected unit for file '$SWAPFILE' (not M or G).
 swapon_line: '$swapon_line'
 swap_file_size_with_unit: '$swap_file_size_with_unit'"
       return 0
@@ -363,7 +364,7 @@ swap_file_size_with_unit: '$swap_file_size_with_unit'"
    swap_file_kernel_reported_size_gb_plus=$(( swap_file_kernel_reported_size_gb_rounded_up + 1 ))
 
    if [ "$swap_file_kernel_reported_size_gb_plus" -ge "$swap_file_target_size_gb" ]; then
-      printf '%s\n' "INFO: File '$SWAPFILE' ($swap_file_size_gb GB) ready. OK."
+      printf '%s\n' "INFO: File '$SWAPFILE' ($swap_file_size_gb GB) created and enabled. OK."
       return 0
    fi
 
